# Site settings
title: Soulheart
description: > 
  Soulheart is the autocorrection/typeahead engine of the future
  from two years ago, or maybe last week
baseurl: "/soulheart" # the subpath of your site, e.g. /blog/
github_username:  sethherr

# Build settings
markdown: kramdown
exclude: [package.json, node_modules, gulpfile.js, react]